version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:4000"
    depends_on:
      - mongo
    env_file:
      - .env.production

  mongo:
    image: mongo:latest
    volumes:
      - /var/www/docker/mongo:/data/db
    ports:
      - "27017:27017"
